name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: npm i -g @railway/cli
    
    - name: Deploy Backend to Railway
      run: |
        cd syriana-student-app/backend
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Deployment Success
      if: success()
      run: |
        echo "✅ Deployment to Railway successful!"
        echo "🚀 Your backend is now live on Railway"
