name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    # Only deploy if CI passes
    needs: []
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy Backend to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "syriana-student-app/backend"
        buildpack: "https://github.com/heroku/heroku-buildpack-nodejs.git"
        healthcheck: "https://${{ secrets.HEROKU_BACKEND_APP_NAME }}.herokuapp.com/api/health"
        delay: 5
        rollbackonhealthcheckfailed: true
      env:
        HD_NODE_ENV: production
        HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}
        HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HD_JWT_EXPIRE: "7d"
        HD_PORT: ${{ secrets.PORT || 5000 }}
    
    - name: Deploy Frontend to Heroku (or Vercel/Netlify)
      run: |
        echo "Frontend deployment"
        echo "Consider using Vercel or Netlify for frontend deployment"
        echo "They offer better performance for React apps"
    
    - name: Deployment status
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "Backend URL: https://${{ secrets.HEROKU_BACKEND_APP_NAME }}.herokuapp.com"
